EncuestaAES/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('autenticacion.urls')),
    path('board/', include('board.urls')),
    path('surveys/', include('djf_surveys.urls'))
]

autenticacion/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('error/', views.error, name='error'),
    path('inicio_sesion/', views.iniciar_sesion, name='inicio_sesion'),
    path('cerrar_sesion/', views.cerrar_sesion, name='cerrar_sesion'),

]

board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.index, name='index'),
    path('resultados', views.resultados, name='resultados'),

]

autenticacion/models.py
from django.db import models

# Create your models here.

board/models.py
from django.db import models

# Create your models here.

autenticacion/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout


def index(request):
    return render(request, 'autenticacion/index.html')


def iniciar_sesion(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("board:index")
        else:
            mensaje = "Credenciales inválidas. Serás redirigido al inicio en 5 segundos."
            return render(request, 'autenticacion/error.html', {'mensaje': mensaje})
    return render(request, 'autenticacion/inicio_sesion.html')


def cerrar_sesion(request):
    logout(request)
    return redirect('/')


def error(request):
    mensaje = "Credenciales inválidas. Serás redirigido al inicio en 5 segundos."
    return render(request, 'autenticacion/error.html', {'mensaje': mensaje})

board/views.py
from django.http import JsonResponse
from django.shortcuts import render


def index(request):
    context = {
        'archivos': "archivos",

    }
    print(context)
    if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
        return JsonResponse(context)
    else:
        return render(request, 'board/index.html', context)

    def index(request):
        context = {
            'archivos': "archivos",

        }
        print(context)
        if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
            return JsonResponse(context)
        else:
            return render(request, 'board/index.html', context)


def resultados(request):
    context = {
        'archivos': "archivos",

    }
    print(context)
    if request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest':
        return JsonResponse(context)
    else:
        return render(request, 'board/resultados.html', context)

templates/autenticacion/cerrar_sesion.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Cerrar Sesión</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% load static %}

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="icon" type="image/png" href="../static/images/OSE.png"> 

    <style>
      /* Estilos personalizados aquí si es necesario */
    </style>
</head>
<body>
    <div class="container">
        <h1>¡Hasta luego!</h1>
        <p>Has cerrado sesión correctamente.</p>
        <a href="{% url 'index' %}" class="btn btn-primary">Volver al Inicio</a>
    </div>

    <!-- Scripts opcionales aquí si es necesario -->
</body>
</html>

templates/autenticacion/error.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Error</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% load static %}

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="icon" type="image/png" href="../static/images/OSE.png"> 

    <style>
      /* Estilos personalizados aquí si es necesario */
    </style>
</head>
<body>
    <div class="container">
        <h1>Error de Autenticación</h1>
        <p>{{ mensaje }}</p>
        <p>Serás redirigido al inicio en 5 segundos.</p>
    </div>

    <!-- Scripts opcionales aquí si es necesario -->
    <script>
        setTimeout(function() {
            window.location.href = "{% url 'index' %}";
        }, 5000);
    </script>
</body>
</html>

templates/autenticacion/index.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Encuestas{% endblock %}</title>
    <link rel="icon" type="image/png" href="/static/images/AES.png"> 

    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% load static %}

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .bd-mode-toggle {
        z-index: 1500;
      }
    </style>
    
    <!-- Custom styles for this template -->
    <link href="{% static 'css/sign-in.css' %}" rel="stylesheet">
  </head>
  <body class="d-flex align-items-center py-4 bg-body-tertiary">
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"></path>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"></path>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"></path>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"></path>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"></path>
      </symbol>
    </svg>


<main class="form-signin w-100 m-auto">
  <form method="post" action="{% url 'inicio_sesion' %}">
    {% csrf_token %}
    <img class="mb-4" src="{% static 'images/AES.jpg' %}" style="width: 100%; height: 100%;">

    <div class="form-floating">
      <input type="text" class="form-control" id="floatingInput" name="username" placeholder="Nombre de Usuario">
      <label for="floatingInput">Nombre de Usuario</label>
    </div>
    <div class="form-floating">
      <input type="password" class="form-control" id="floatingPassword" name="password" placeholder="Contraseña">
      <label for="floatingPassword">Password</label>
    </div>


    <button class="btn btn-primary w-100 py-2" type="submit">Ingreso</button>

  </form>
</main>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/color-modes.js' %}"></script>
    </body>
</html>

templates/autenticacion/inicio_sesion.html
<!DOCTYPE html>
<head>
<title>AID - Teleimpresores</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/static/css/dashboard.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="icon" type="image/png" href="/static/images/AES.png">    
<style>
html,body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
.centered-image {
    display: block;
    margin-left: auto;
    margin-right: auto;
}
</style>
</head>
<body class="w3-light-grey">

<!-- Top container -->
<div class="w3-bar w3-top w3-black w3-large" style="z-index:4">
  <button class="w3-bar-item w3-button w3-hide-large w3-hover-none w3-hover-text-light-grey" onclick="w3_open();"><i class="fa fa-bars"></i>  Menu</button>
  <span class="w3-bar-item w3-right w3-text-black">Logo</span>
</div>

<!-- Sidebar/menu -->
<nav class="w3-sidebar w3-collapse w3-white w3-animate-left" style="z-index:3;width:300px;" id="mySidebar"><br>
  <div class="w3-container w3-row">
    <div class="w3-col s4">
      <img src="/static/images/avatar2.png" class="w3-circle w3-margin-right" style="width:46px" alt="">
    </div>
    <div class="w3-col s8 w3-bar">
    <span>Bienvenido, <strong>{{ user.username }}</strong></span><br><br>
    <a href="{% url 'cerrar_sesion' %}" class="w3-button w3-teal w3-small">Cerrar Sesión</a>

</div>


  </div>
  <hr>
    
  <div class="w3-container">
    <h5 style="text-align: center;"><strong>Dashboard</strong></h5>
  </div>
  <div class="w3-bar-block">
    <a href="#" class="w3-bar-item w3-button w3-padding-16 w3-hide-large w3-dark-grey w3-hover-black" onclick="w3_close()" title="close menu"><i class="fa fa-remove fa-fw"></i>  Close Menu</a>
    <a href="{% url 'board:index' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-dashboard fa-fw"></i>  Dashboard</a>
      <hr>
      <a href="{% url 'board:resultados' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-dashboard fa-fw"></i>  Resultados</a>
      <h5 style="text-align: center;"><strong></strong></h5>
{#        <a href="{% url 'informe:index' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-file fa-fw"></i>Informe</a>#}
{#        <a href="{% url 'rutas:index' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-map-marker fa-fw"></i>Períodos de Mtto.</a>#}
{#        <hr>#}
{#        <h5 style="text-align: center;"><strong>PPCC</strong></h5>#}
{#        <a class="w3-bar-item w3-button w3-padding"><i class="fa fa-globe fa-fw"></i>Localización</a>#}
{#          <div style="padding-left: 20px;"> <!-- Ajusta el valor de padding-left según lo desees -->#}
{#                <a href="{% url 'corePPCC:index' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-globe fa-fw"></i>Regiones</a>#}
{#            </div>#}
{#          <div style="padding-left: 20px;"> <!-- Ajusta el valor de padding-left según lo desees -->#}
{#                    <a href="{% url 'informe:index' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-globe fa-fw"></i>Departamentos</a>#}
{#                </div>#}
{#          <div style="padding-left: 20px;"> <!-- Ajusta el valor de padding-left según lo desees -->#}
{#                    <a href="{% url 'informe:index' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-globe fa-fw"></i>Localidades</a>#}
{#                </div>#}
{#          <div style="padding-left: 20px;"> <!-- Ajusta el valor de padding-left según lo desees -->#}
{#                    <a href="{% url 'informe:index' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-globe fa-fw"></i>Sectores</a>#}
{#                </div>#}
{#        <a  class="w3-bar-item w3-button w3-padding"><i class="fa fa-microchip fa-fw"></i>Equipamiento</a>#}
{#          <div style="padding-left: 20px;"> <!-- Ajusta el valor de padding-left según lo desees -->#}
{#                    <a href="{% url 'informe:index' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-microchip fa-fw"></i>Marcas Medidores</a>#}
{#                </div>#}
{#              <div style="padding-left: 20px;"> <!-- Ajusta el valor de padding-left según lo desees -->#}
{#                        <a href="{% url 'informe:index' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-microchip fa-fw"></i>Modelos Medidores</a>#}
{#                    </div>#}
{#              <div style="padding-left: 20px;"> <!-- Ajusta el valor de padding-left según lo desees -->#}
{#                        <a href="{% url 'informe:index' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-microchip fa-fw"></i>Gateway</a>#}
{#                    </div>#}
{#              <div style="padding-left: 20px;"> <!-- Ajusta el valor de padding-left según lo desees -->#}
{#                        <a href="{% url 'informe:index' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-microchip fa-fw"></i>Módulo</a>#}
{#                    </div>#}
{#              <a class="w3-bar-item w3-button w3-padding"><i class="fa fa-database fa-fw"></i>Lecturas</a>#}
{#                  <div style="padding-left: 20px;"> <!-- Ajusta el valor de padding-left según lo desees -->#}
{#                        <a href="{% url 'informe:index' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-database fa-fw"></i>Lecturas</a>#}
{#                    </div>#}
{#                  <div style="padding-left: 20px;"> <!-- Ajusta el valor de padding-left según lo desees -->#}
{#                            <a href="{% url 'informe:index' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-database fa-fw"></i>Transmisiones</a>#}
{#                        </div>#}
{#                  <a class="w3-bar-item w3-button w3-padding"><i class="fa fa-binoculars fa-fw"></i>Consultas</a>#}
{#                              <div style="padding-left: 20px;"> <!-- Ajusta el valor de padding-left según lo desees -->#}
{#                                    <a href="{% url 'informe:index' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-binoculars fa-fw"></i>Gateway Activos</a>#}
{#                                </div>#}
{#                <div style="padding-left: 20px;"> <!-- Ajusta el valor de padding-left según lo desees -->#}
{#                    <a href="{% url 'informe:index' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-binoculars fa-fw"></i>Módulos Últ. lectura 0</a>#}
{#                </div>#}
{#              <div style="padding-left: 20px;"> <!-- Ajusta el valor de padding-left según lo desees -->#}
{#                  <a href="{% url 'informe:index' %}" class="w3-bar-item w3-button w3-padding"><i class="fa fa-binoculars fa-fw"></i>Informe Técnico</a>#}
{#              </div>#}
        <hr>
</div>
    <div class="w3-container">
    <img src="/static/images/AES.png" style="width:150px" class="centered-image">
  </div>
</nav>


<!-- Overlay effect when opening sidebar on small screens -->
<div class="w3-overlay w3-hide-large w3-animate-opacity" onclick="w3_close()" style="cursor:pointer" title="close side menu" id="myOverlay"></div>

<!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:300px;margin-top:43px;">

  <!-- Header -->
  <header class="w3-container" style="padding-top:22px"></header>
{% block main_content %}
  
    
    
    
<script>

    const mySidebar = document.getElementById("mySidebar");

    const overlayBg = document.getElementById("myOverlay");

    function w3_open() {
  if (mySidebar.style.display === 'block') {
    mySidebar.style.display = 'none';
    overlayBg.style.display = "none";
  } else {
    mySidebar.style.display = 'block';
    overlayBg.style.display = "block";
  }
}

function w3_close() {
  mySidebar.style.display = "none";
  overlayBg.style.display = "none";
}
</script>
    </div>
</body>
{% endblock %}

templates/board/index.html
{% extends 'autenticacion/inicio_sesion.html' %}
{% block main_content %}
 <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<iframe id="surveyFrame" src="http://127.0.0.1:8000/surveys/dashboard/" width="100%" style="border:none;"></iframe>

<script>
    var surveyFrame = document.getElementById('surveyFrame');

    function adjustIframeHeight() {
        surveyFrame.style.height = surveyFrame.contentWindow.document.body.scrollHeight + 'px';
    }

    surveyFrame.onload = adjustIframeHeight;
</script>
{% endblock %}

templates/board/resultados.html
{% extends 'autenticacion/inicio_sesion.html' %}
{% block main_content %}
 <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<iframe id="surveyFrame" src="http://127.0.0.1:8000/surveys/dashboard/summary/survey/encuesta-satisfaccion-al-cliente-servicio-a/" width="100%" style="border:none;"></iframe>

<script>
    var surveyFrame = document.getElementById('surveyFrame');

    function adjustIframeHeight() {
        surveyFrame.style.height = surveyFrame.contentWindow.document.body.scrollHeight + 'px';
    }

    surveyFrame.onload = adjustIframeHeight;
</script>
{% endblock %}